mesos_master:
    image: daocloud.io/adolphlwq/docker-mesos-master:gic-13f0e95
    net: "host"
    privileged: true
    volumes:
      - /var/mesos:/var/mesos
    container_name: mesos_master
    env_file: mesos_master_env

marathon:
    image: mesoscloud/marathon
    net: "host"
    privileged: true
    container_name: marathon
    env_file: marathon_env

zookeeper:
    image: daocloud.io/adolphlwq/docker-zookeeper:master-81e69c8
    net: host
    privileged: true
    container_name: zookeeper

dnsserver:
    image: linkerrepository/linker_mesos_dns
    net: "host"
    privileged: true
    volumes:
        - ./config:/linker/config
    container_name: mesosdns

linker_router:
    image: linkerrepository/linker_router
    net: host
    privileged: true
    container_name: linker_router
